import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Flex } from "@chakra-ui/react";
import SideBar from "@/components/sideBar";
import HomeHeader from "@/components/HomeHeader";
import CommunityCard from "@/components/CommunityCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <SideBar />

        <Flex padding={12} flexDirection="column" w="100%">
          <HomeHeader />
          <Flex
            fontWeight="700"
            fontSize="32px"
            padding="32px 0"
          >

            <h1>Você pode experimentar...</h1>
          </Flex>

          <Flex
            id="community-grid"
            
          >
            <CommunityCard
              title={"Briofiteiros de plantão 🌱"}
              description="A maior comunidade de botânicos do 4.communitys. Aqui você encontrará tudo relacionado a plantinhas e a plantões!!!"
              imgUrl={"https://joaobidu.com.br/wp-content/uploads/2023/04/plantas-que-promovem-bem-estar-em-casa.jpg"}
              type="private"
            />
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
